spring:
    datasource:
        driverClassName: org.h2.Driver
        password: admin
        username: admin
        url: jdbc:h2:mem:companiondb
    h2:
        console:
            path: /h2-companion-console
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
            data-locations: classpath*:import-*-loadout.sql
