spring:
    datasource:
        driverClassName: org.h2.Driver
        password: admin
        url: jdbc:h2:mem:companiondb
        username: admin
    h2:
        console:
            enabled: true
            path: /h2-companion-console
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
            data-locations: classpath*:import-*-loadout.sql
